from data_structures.LinkedList import Node, LinkedList

# testing out the linked list class
first_node = Node(5)
second_node = Node(67)
third_node = Node(6)
linked_list = LinkedList(first_node)
linked_list.add_to_front(second_node)
linked_list.add_to_front(third_node)
print(linked_list)
linked_list.remove_last_node()
print(linked_list)
linked_list.remove_last_node()
print(linked_list)
linked_list.remove_last_node()
print(linked_list)
linked_list.add_to_front(second_node)
linked_list.add_to_front(third_node)
print(linked_list)
linked_list.remove_first_node()
print(linked_list)
linked_list.remove_first_node()
print(linked_list)
print(linked_list.remove_first_node())
